version: '3.7'

services:
    server:
      build:
        context: ./
        dockerfile: ./server/Dockerfile
      command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done;
                        python manage.py migrate;
                        gunicorn config.wsgi -c ./config/gunicorn.py"
      volumes:
        - ./server:/server
      ports:
        - "8000:8000"
      depends_on:
        - db
      environment:
        DEBUG: 'False'
        DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'
        SECRET_KEY: "87!^h6qwybfya*g#7wn2!6kq)_0m3gz57*b4#*)!+opey3yek*"

    db:
        image: postgres:12.4-alpine
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    swagger-ui:
      image: swaggerapi/swagger-ui
      environment:
        SWAGGER_JSON: '/docs/openapi.yaml'
      ports:
        -   "9000:8080"
      volumes:
        - ./docs:/docs
