# Generated by Django 2.2.10 on 2021-08-22 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_answerchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(null=True, verbose_name='Ответ текстом')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время первого ответа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления ответа')),
                ('choice_answers', models.ManyToManyField(blank=True, null=True, related_name='answers', to='polls.AnswerChoice', verbose_name='Выбранные вариант(ы) ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.Question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователя',
            },
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='single_user_answer_by_question'),
        ),
    ]
